<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SUBSCRIBE_popup-subcription-closes-icon_bd6480</name>
   <tag></tag>
   <elementGuidId>8fab2416-5b21-4463-a6b0-9ea9bafa6724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='popup-subcription-closes-icon-b599a993-6849-40b6-b7aa-5ed707ab8b10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-image-type</name>
      <type>Main</type>
      <value>circle_fill</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.bronto.com/popup/eac4422f-79b9-4308-9e87-ccd41cf97942/b599a993-6849-40b6-b7aa-5ed707ab8b10/close_circle_fill.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popup-subcription-closes-icon-b599a993-6849-40b6-b7aa-5ed707ab8b10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Popup Close Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-subcription-closes-icon-b599a993-6849-40b6-b7aa-5ed707ab8b10&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='popup-subcription-closes-icon-b599a993-6849-40b6-b7aa-5ed707ab8b10']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-subcription-backgrounds-container-b599a993-6849-40b6-b7aa-5ed707ab8b10']/div[8]/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.bronto.com/popup/eac4422f-79b9-4308-9e87-ccd41cf97942/b599a993-6849-40b6-b7aa-5ed707ab8b10/close_circle_fill.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
