<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscriptionPopupWindow</name>
   <tag></tag>
   <elementGuidId>169c0422-db2c-45f7-9de6-ad1b4aab78d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-subcription-backgrounds-container-b599a993-6849-40b6-b7aa-5ed707ab8b10']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
